inherit_gem:
  rubocop-shopify: rubocop.yml

require:
- rubocop-performance
- rubocop-rake
- rubocop-minitest

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.7.2

Style/MethodCallWithArgsParentheses:
  IgnoredMethods:
    - not_to
    - prepend
    - puts
    - raise
    - to
    - warn
    - yield
