up:
  - homebrew:
    - sdl2
  - ruby: 3.0.2
  - bundler

commands:
  run: bin/run

  test: |
    if [[ $# -eq 0 ]]; then
      bin/rake test
    else
      ruby -Itest "$@"
    fi

  style: bin/rubocop
